### ISSUE TITLE
Interactive flexagon editing

### ISSUE THREAD

**Issue by ao2** [michibo/hexaflexa#2]
Hi Michael,

This is not an actual issue, it's just a comment, so feel free to close it.

I am popping by only to report that it's even possible to edit flexagons interactively in Inkscape by using a specially crafted SVG file, check out https://ao2.it/blog/2018/01/31/fun-flexagons-and-svg

Ciao,
   Antonio

**Comment by michibo** [comment]
Dear Antonio,

thank you! That looks really cool. 

As a further idea: It would be great to have a tool that also shows you the three sides there the triangles are not in the right configuration. This way you could maybe make hexaflexagons where the 'wrong' configurations also show a relatively nice picture. Just as in one of the vihart videos 'Hexaflexagon safety guide' 2:45 and after.

All best,
Michael

**Comment by ao2** [comment]
Yes, I too thought about that after watching "The symmetry within the trihexaflexagon, with Simon Pampena" https://youtu.be/NBJrGbbxceU?t=4m38s

Anyways, I don't know when I'll be able to add that to flexagon-toolkit, so for now I added a TODO entry https://git.ao2.it/flexagon-toolkit.git/commitdiff/9e3b6f79607747cd0e42ee5ab93a176f40826067

If you ever got to it yourself, let me know.

Ciao ciao,
   Antonio

**Comment by ao2** [comment]
Hi @michibo just a heads-up about the "backfaces" feature: I added it to the latest code at https://git.ao2.it/flexagon-toolkit.git/

Pictures at https://twitter.com/ao2it/status/1012357163774283782

Any bug report is more than welcome :smile: 

Ciao,
   Antonio
